# Generated by Django 5.0.7 on 2024-07-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchAgainm',
            new_name='watchAgain',
        ),
    ]
